export const ADD_MOVIE_ACTION_TYPE = "ADD_MOVIE_ACTION_TYPE";

export const REMOVE_MOVIE_ACTION_TYPE = "REMOVE_MOVIE_ACTION_TYPE";

export const RESET_MOVIES_ACTION_TYPE = "RESET_MOVIES_ACTION_TYPE";
